<?php

namespace AppBundle\Repository;

/**
 * EdgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdgeRepository extends \Doctrine\ORM\EntityRepository
{
}
