<?php

namespace AppBundle\Repository;

/**
 * GameTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameTableRepository extends \Doctrine\ORM\EntityRepository
{
}
