<?php

namespace AppBundle\Repository;

/**
 * VertexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VertexRepository extends \Doctrine\ORM\EntityRepository
{
}
